const lang = {
    en: {
        search : "Search",
        SearchPlaceholder: "What Would You Like to Watch Today",
        SignOut : "SignOut",
        Play: "Play",
        MoreInfo: "More Info",
        home : "Home",
        signUpNow: "Sign up now.",
        signInNow: "Sign in now",
        signIn: "Sign In",
        signUp:"Sign Up",
        newToNetflix: "New to Netflix?",
        rememberMe: "Remember Me",
        email: "Email Address",
        password: "Password",
        forgotPassword: "Forgot Password?",
        continue: "Continue",
        fullName: "Full Name",
        emailOrPhone: "Email or mobile number",
        alreadyUser: "Already a User?",

    },
    hindi: {
        search : "खोज",
        SearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
        SignOut : "साइन आउट",
        Play: "चलाओ",
        MoreInfo: "जानकारी",
        home : "मुखपृष्ठ",
        signUpNow: "अभी साइन अप करें।",
        signInNow: "अभी साइन इन करें",
        signIn:"साइन इन करें",
        signUp:"साइन अप करें",
        newToNetflix: "नेटफ्लिक्स पर नए हैं?",
        rememberMe: "मुझे याद रखें",
        email: "ईमेल पता",
        password: "पासवर्ड",
        forgotPassword: "पासवर्ड भूल गए?",
        continue: "जारी रखें",
        fullName: "पूरा नाम",
        emailOrPhone: "ईमेल या मोबाइल नंबर",
        alreadyUser: "पहले से ही उपयोगकर्ता हैं?",

    },
    spanish : {
        search : "buscar",
        SearchPlaceholder: "¿Qué te gustaría ver hoy?",
        SignOut: "Desconectar",
        Play : "reproducir película",
        MoreInfo: "más información",
        home: "Inicio",
        signIn:"Iniciar sesión",
        signUpNow: "Regístrate ahora.",
        signInNow: "Inicia sesión ahora",
        signUp:"Registrarse",
        newToNetflix: "¿Nuevo en Netflix?",
        rememberMe: "Recuérdame",
        email: "Dirección de correo",
        password: "Contraseña",
        forgotPassword: "¿Olvidaste tu contraseña?",
        continue: "Continuar",
        fullName: " Nombre completo",
        emailOrPhone: "Correo o número de teléfono",
        alreadyUser: "¿Ya tienes una cuenta?",

    }
}


export default lang;